# Generated by Django 4.1.2 on 2023-01-19 16:53

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', users.models.VarCharField(
                    max_length=100, primary_key=True, serialize=False)),
                ('name', users.models.VarCharField(blank=True, max_length=30)),
                ('surname', users.models.VarCharField(blank=True, max_length=30)),
                ('mail', users.models.VarCharField(max_length=40, unique=True)),
                ('money', models.DecimalField(
                    decimal_places=2, default=0, max_digits=6)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'USERS',
            },
        ),
    ]
