-- clear data;

DELETE FROM BIDS;
DELETE FROM SCHOOLWORKS;
DELETE FROM SCHOOLCLASSES;
DELETE FROM CATEGORIES;

-- school classes;
INSERT INTO SCHOOLCLASSES(NAME, START_YEAR)
VALUES ('1A', 2019);
INSERT INTO SCHOOLCLASSES(NAME, START_YEAR)
VALUES ('1B', 2019);
INSERT INTO SCHOOLCLASSES(NAME, START_YEAR)
VALUES ('1A', 2020);
INSERT INTO SCHOOLCLASSES(NAME, START_YEAR)
VALUES ('1B', 2020);

-- NFT categories;
INSERT INTO CATEGORIES(CATEGORY_ID, NAME)
VALUES (0, 'Uncategorized');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME)
VALUES (1, 'Landscapes');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME)
VALUES (2, 'Nature');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME)
VALUES (3, 'Space');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME)
VALUES (4, 'Animals');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME)
VALUES (5, 'People');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME)
VALUES (6, 'Machines');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME)
VALUES (7, 'Abstract');

-- NFTs;
INSERT INTO SCHOOLWORKS(NFT_ID, TOKEN, AUTHOR_NAME, AUTHOR_SURNAME, GRAPHIC, START_DATE, END_DATE, CURRENT_PRICE, CATEGORY_ID, SCHOOLCLASS_ID)
VALUES (0, 'token', 'Mariusz', 'Pudzianowski', NULL, DATE '2023-01-01', DATE '2023-02-25', 8, 0, 1);
INSERT INTO SCHOOLWORKS(NFT_ID, TOKEN, AUTHOR_NAME, AUTHOR_SURNAME, GRAPHIC, START_DATE, END_DATE, CURRENT_PRICE, CATEGORY_ID, SCHOOLCLASS_ID)
VALUES (1, 'token', 'Robert', 'Kubica', NULL, DATE '2023-01-01', DATE '2023-02-25', 2, 0, 1);
INSERT INTO SCHOOLWORKS(NFT_ID, TOKEN, AUTHOR_NAME, AUTHOR_SURNAME, GRAPHIC, START_DATE, END_DATE, CURRENT_PRICE, CATEGORY_ID, SCHOOLCLASS_ID)
VALUES (2, 'token', 'Robert', 'Lewandowski', NULL, DATE '2023-01-01', DATE '2023-02-25', 4, 0, 2);
INSERT INTO SCHOOLWORKS(NFT_ID, TOKEN, AUTHOR_NAME, AUTHOR_SURNAME, GRAPHIC, START_DATE, END_DATE, CURRENT_PRICE, CATEGORY_ID, SCHOOLCLASS_ID)
VALUES (3, 'token', 'Zbigniew', 'Boniek', NULL, DATE '2023-01-01', DATE '2023-02-25', 3, 2, 2);
INSERT INTO SCHOOLWORKS(NFT_ID, TOKEN, AUTHOR_NAME, AUTHOR_SURNAME, GRAPHIC, START_DATE, END_DATE, CURRENT_PRICE, CATEGORY_ID, SCHOOLCLASS_ID)
VALUES (4, 'token', 'Leszek', 'Możdżer', NULL, DATE '2023-01-01', DATE '2023-02-25', 10, 0, 3);
INSERT INTO SCHOOLWORKS(NFT_ID, TOKEN, AUTHOR_NAME, AUTHOR_SURNAME, GRAPHIC, START_DATE, END_DATE, CURRENT_PRICE, CATEGORY_ID, SCHOOLCLASS_ID)
VALUES (5, 'token', 'Robert', 'Makłowicz', NULL, DATE '2023-01-01', DATE '2023-02-25', 5, 0, 4);

-- Python scripts adds graphics, don't write any SQL for that;
