# Generated by Django 4.1.2 on 2023-01-19 16:53

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftCategory',
            fields=[
                ('category_id', models.AutoField(
                    primary_key=True, serialize=False)),
                ('name', users.models.VarCharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'CATEGORIES',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('schoolclass_id', models.AutoField(
                    primary_key=True, serialize=False)),
                ('name', users.models.VarCharField(max_length=2)),
                ('start_year', models.IntegerField()),
            ],
            options={
                'db_table': 'SCHOOLCLASSES',
                'unique_together': {('name', 'start_year')},
            },
        ),
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('nft_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', users.models.VarCharField(
                    editable=False, max_length=100, null=True, unique=True)),
                ('author_name', users.models.VarCharField(max_length=15)),
                ('author_surname', users.models.VarCharField(max_length=20)),
                ('graphic', models.BinaryField(editable=True, max_length=1000000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('current_price', models.DecimalField(
                    decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.nftcategory')),
                ('schoolclass', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.schoolclass')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'SCHOOLWORKS',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_winner', models.BooleanField(default=False)),
                ('date_winner', models.DateTimeField(null=True)),
                ('nft', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.nft')),
                ('user', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'BIDS',
            },
        ),
    ]
